### PR TITLE
Add chrome extension

### PR DESCRIPTION
**Pull request by jessestricker**
Hey, I've developed a small Chrome Extension, which opens a new tab with the print url, when you click on the extension's icon in the upper right.

It also handles Gists: tabs navigate to "gitprint.com/USER/HASH/raw", so they also work.

### CODE REVIEW

**Comment by adamburmister** [comment]
@jessestricker Wow, a contrib! Thanks.
Do you have source for the extension? I'd love to include it but I'm not 100% comfortable merging in a binary because of potential security implications

**Comment by jessestricker** [comment]
Sure, I forgot.
I've added a new folder for the source code.

**Comment by jessestricker** [comment]
And what about this houndci warning? Do I need to address those before merging?

**Comment by jessestricker** [comment]
I'm currently closing some old PRs. This one I opened years ago and I no longer have the source for the binary.

Sorry to anyone who was interested in this.

**Pull request closed without merging**
